language: node_js

os:
  - windows
  - linux
  - osx

node_js:
  - 6
  - 8
  - 10

env:
  - ZF_TRAVIS_COMMAND=test:javascript:units

matrix:
  include:
    - os: windows
      node_js: 10
      env: ZF_TRAVIS_COMMAND=test:javascript:browserstack
    - os: linux
      node_js: 10
      env: ZF_TRAVIS_COMMAND=test:javascript:browserstack
    - os: osx
      node_js: 10
      env: ZF_TRAVIS_COMMAND=test:javascript:browserstack

before_install: npm install -g npm@latest
install: npm ci
script: npm run $ZF_TRAVIS_COMMAND

notifications:
  email: false
