language: node_js
cache: yarn

os:
  - windows
  - linux
  - osx

node_js:
  - 6
  - 8
  - 10

env:
  global:
    - YARN_GPG=no
  matrix:
    - ZF_TRAVIS_COMMAND=test

matrix:
  include:
    - os: linux
      node_js: 10
      env: ZF_TRAVIS_COMMAND=test:javascript:browserstack

install: yarn
script: yarn run $ZF_TRAVIS_COMMAND

notifications:
  email: false
