language: node_js

os:
  - windows
  - linux
  - osx

node_js:
  - 6
  - 8
  - 10
  - 11

env:
  - ZF_TRAVIS_COMMAND=test

matrix:
  include:
    - os: linux
      node_js: stable
      env: ZF_TRAVIS_COMMAND=test:javascript:browserstack

install: yarn
script: yarn run $ZF_TRAVIS_COMMAND

notifications:
  email: false
